CREATE TABLE users(
id INT PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(255),
password_hash VARCHAR(255) NOT NULL
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE articles(
id INT PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(255) NOT NULL,
body TEXT NOT NULL,
category VARCHAR(100) NOT NULL,
submitted_by INT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (submitted_by) REFERENCES users(id) ON DELETE CASCADE
);